#!/bin/sh

set -e

. /usr/share/debconf/confmodule

db_get systrace/createdev
if [ "$RET" = "true" ]; then
    # check if the file already exists
    if [ -c /dev/systrace ]; then
	exit 0
    fi

    # check if we use devfs
    if grep -q '^devfs' /proc/mounts 2>/dev/null; then
	: using devfs so continue
    else
	exit 0
    fi

    if which MAKEDEV > /dev/null; then
	echo "Creating character device: /dev/systrace"
	if [ -f /dev/systrace ] ; then
	    rm -f /dev/systrace
	fi
	cd /dev/ && MAKEDEV systrace
    fi
fi

#DEBHELPER#
